# .github/release.yml

changelog:
  categories:
    - title: Changes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Dependabot
      labels:
        - dependencies
