name: Deploy to production
on:
  release:
    types: [released]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: ${{ vars.KUNOICHI_REMOTE_URL }}
    steps:
steps:
  - uses: actions/checkout@v2
  - run: |
      echo "ths is env=${{ env.env_1 }}"
